# Generated by Django 3.2.2 on 2021-05-21 07:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_stories'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Stories',
        ),
    ]
